<a href="https://colab.research.google.com/github/ShaikhYusufAli/Fake-News-Prediction/blob/main/fake_news_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df_job=pd.read_csv('/content/fake_job_postings.csv')
df_job.head(2)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0.0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0.0

In [3]:
df_job.columns

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent'],
      dtype='object')

In [4]:
df_job.isnull().sum()

job_id                    0
title                     0
location                123
department             4321
salary_range           5762
company_profile        1517
description               0
requirements            935
benefits               2739
telecommuting             0
has_company_logo          0
has_questions             0
employment_type        1647
required_experience    2809
required_education     3122
industry               2062
function               2559
fraudulent                1
dtype: int64

In [5]:
df_job.dtypes

job_id                   int64
title                   object
location                object
department              object
salary_range            object
company_profile         object
description             object
requirements            object
benefits                object
telecommuting            int64
has_company_logo         int64
has_questions            int64
employment_type         object
required_experience     object
required_education      object
industry                object
function                object
fraudulent             float64
dtype: object

In [6]:
df_job['department'] = df_job['department'].fillna(df_job['department'].mode()[0])

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn import feature_selection
from sklearn.impute import SimpleImputer

In [9]:
data_cat_imp=SimpleImputer(strategy="constant",fill_value="Missing")
cat_imp_feature=["title","location","department","salary_range","company_profile","description","requirements","benefits",
                 "employment_type","required_experience","required_education","industry","function"]

# Filling the Numerical values through existing value
data_num_imp=SimpleImputer(strategy="constant",fill_value=None)
num_imp_feature =["job_id","telecommuting","has_company_logo","has_questions","fraudulent"]

# Transforming into column
data_imp_trans=ColumnTransformer([("data_cat_imp",data_cat_imp,cat_imp_feature),
                                 ("data_num_imp",data_num_imp,num_imp_feature)])

# Transforming and assigning the data
transformed_data=data_imp_trans.fit_transform(df_job)
transformed_data

array([['Marketing Intern', 'US, NY, New York', 'Marketing', ..., 1.0,
        0.0, 0.0],
       ['Customer Service - Cloud Video Production', 'NZ, , Auckland',
        'Success', ..., 1.0, 0.0, 0.0],
       ['Commissioning Machinery Assistant (CMA)', 'US, IA, Wever',
        'Sales', ..., 1.0, 0.0, 0.0],
       ...,
       ['Front End Web Developer', 'IL, TA, Tel Aviv', 'Sales', ..., 1.0,
        1.0, 0.0],
       ['Systems Engineer (Infrastructure)', 'IE, L, Dublin', 'Sales',
        ..., 1.0, 0.0, 0.0],
       ['Product Admin Executive / Intern', 'GB, , ', 'Festicket', ...,
        1.0, 0.0, 0.0]], dtype=object)

In [10]:
df_job_transformed_data=pd.DataFrame(transformed_data,
                         columns=["title","location","department","salary_range","company_profile","description",
                                  "requirements","benefits", "employment_type","required_experience","required_education",
                                  "industry","function","job_id","telecommuting","has_company_logo","has_questions",
                                  "fraudulent"])

In [11]:
df_job_transformed_data.head(2)

,title,location,department,salary_range,company_profile,description,requirements,benefits,employment_type,required_experience,required_education,industry,function,job_id,telecommuting,has_company_logo,has_questions,fraudulent
0,Marketing Intern,"US, NY, New York",Marketing,Missing,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,Missing,Other,Internship,Missing,Missing,Marketing,1.0,0.0,1.0,0.0,0.0
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,Missing,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,Full-time,Not Applicable,Missing,Marketing and Advertising,Customer Service,2.0,0.0,1.0,0.0,0.0

In [12]:
df_job_transformed_data.isna().sum()
X_trans = df_job_transformed_data.drop("fraudulent",axis=1)
y_trans = df_job_transformed_data.fraudulent
y_trans=y_trans.astype('int')

#shape(row,column) of features and label
X_trans.shape, y_trans.shape,X_trans.columns

((6841, 17),
 (6841,),
 Index(['title', 'location', 'department', 'salary_range', 'company_profile',
        'description', 'requirements', 'benefits', 'employment_type',
        'required_experience', 'required_education', 'industry', 'function',
        'job_id', 'telecommuting', 'has_company_logo', 'has_questions'],
       dtype='object'))

In [13]:
X_trans

,title,location,department,salary_range,company_profile,description,requirements,benefits,employment_type,required_experience,required_education,industry,function,job_id,telecommuting,has_company_logo,has_questions
0,Marketing Intern,"US, NY, New York",Marketing,Missing,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,Missing,Other,Internship,Missing,Missing,Marketing,1.0,0.0,1.0,0.0
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,Missing,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,Full-time,Not Applicable,Missing,Marketing and Advertising,Customer Service,2.0,0.0,1.0,0.0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",Sales,Missing,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,Missing,Missing,Missing,Missing,Missing,Missing,3.0,0.0,1.0,0.0
3,Account Executive - Washington DC,"US, DC, Washington",Sales,Missing,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,4.0,0.0,1.0,0.0
4,Bill Review Manager,"US, FL, Fort Worth",Sales,Missing,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,5.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6836,Lead Generation Specialist,"US, PA, Harrisburg",Sales,Missing,Ameritech Media wants to give industry thought...,Ameritech Media is a full-service marketing fi...,Skills/Qualifications/Education:1+ year(s) sal...,Base pay of $12/hour plus commission and bonus...,Full-time,Associate,Missing,Marketing and Advertising,Sales,6837.0,0.0,1.0,0.0
6837,Senior Software Engineer,"US, CA, San Francisco",Sales,Missing,Missing,"At Healthvana, we believe healthcare should wo...",The technical stuffFluency in Python and SQLIn...,"We don’t care where you live, as long as you d...",Full-time,Mid-Senior level,Missing,Internet,Information Technology,6838.0,1.0,0.0,0.0
6838,Front End Web Developer,"IL, TA, Tel Aviv",Sales,Missing,PowToon (#URL_84da40102d63eebf414f1476e73cf04c...,"As PowToon's Frontend Web Developer, your main...","Excellent HTML, HTML5, CSS 3 programming skill...",Missing,Full-time,Mid-Senior level,Unspecified,Internet,Information Technology,6839.0,0.0,1.0,1.0
6839,Systems Engineer (Infrastructure),"IE, L, Dublin",Sales,Missing,Intercom (#URL_cb674f93cbcd215a3a0a57a8615a565...,About The JobThe infrastructure team are respo...,Missing,Competitive salaryEquity in a fast growing sta...,Missing,Missing,Missing,Missing,Missing,6840.0,0.0,1.0,0.0
6840,Product Admin Executive / Intern,"GB, ,",Festicket,Missing,Playfair Capital is an early stage technology ...,"Enjoying a position in a fast-growing market, ...",Missing,Missing,Missing,Missing,Missing,Missing,Missing,6841.0,0.0,1.0,0.0

In [14]:
one_hot=OneHotEncoder()
clf_trans=ColumnTransformer([("one_hot",one_hot,cat_imp_feature)],remainder="passthrough")
X_trans_fin=clf_trans.fit_transform(X_trans)
np.array(X_trans_fin)

array(<6841x23259 sparse matrix of type '<class 'numpy.float64'>'
	with 105063 stored elements in Compressed Sparse Row format>,
      dtype=object)

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X_trans_fin,y_trans,test_size=0.23, random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((5267, 23259), (1574, 23259), (5267,), (1574,))

In [16]:
model_rfm=RandomForestClassifier()

#fitting the data into model
model_rfm.fit(X_train,y_train)

RandomForestClassifier()

In [17]:
print(f"Fake Job Random Forest Model Accuracy : {model_rfm.score(X_test,y_test)*100:.2f}%")

Fake Job Random Forest Model Accuracy : 98.28%

In [18]:
y_pred_rfm=model_rfm.predict(X_test)
y_pred_rfm

array([0, 0, 0, ..., 0, 0, 0])

In [19]:
from sklearn.metrics import classification_report

In [20]:
print(classification_report(y_test,y_pred_rfm))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1521
           1       1.00      0.49      0.66        53

    accuracy                           0.98      1574
   macro avg       0.99      0.75      0.82      1574
weighted avg       0.98      0.98      0.98      1574